<?xml version="1.0" encoding="utf-8"?> 

<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <Configuration>Release</Configuration>
  </PropertyGroup>
  
  <Target Name="Build"> 
    <Message Text="Starting to Build '$(SolutionDir)$(SolutionFileName)' in '$(Configuration)' mode"/> 
    <MSBuild Projects="$(SolutionDir)$(SolutionFileName)" Properties="Configuration=$(Configuration)" /> 
  </Target> 
</Project>